### ISSUE TITLE
database is uninitialized and password option is not specified

### ISSUE THREAD

**Issue by 0xsven** [linssen/docker-craft-cms#1]
I followed your instructions and now I am getting an error:

```
db_1      | error: database is uninitialized and password option is not specified
db_1      |   You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
dockercraftcms_db_1 exited with code 1
```

Any idea what I have done wrong?

**Comment by linssen** [comment]
Try adding `MYSQL_ROOT_PASSWORD: docker` to the DB environment, and rebuilding?

**Comment by 0xsven** [comment]
@linssen that was fast. It works! Thank you

**Comment by linssen** [comment]
Awesome! Feel free to send a pull request for the fix ;)
