### ISSUE TITLE
Following instructions results in error

### ISSUE THREAD

**Issue by yn5** [linssen/docker-craft-cms#3]
1. Unzip the CraftCMS download into web, overwriting the craft and public folders therein.
2. Install Docker
3. Run docker-compose up

The third step results in: `Unsupported config option for services service: 'web'`

**Comment by linssen** [comment]
What do your docker logs say? Are you running this on OS X / Win?

**Comment by yn5** [comment]
There is no Docker container running, so no logs as far as I can tell.

**Comment by linssen** [comment]
Are you running this on OS X or Win, and is it Docker Toolbox?

**Comment by yn5** [comment]
@linssen Sorry for answering only half your question: Running Ubuntu 14.04.3

**Comment by linssen** [comment]
Could be that your docker-compose is out of date. If you're below 1.6, it'll complain about the yaml (check with `docker-compose --version`. Try updating and running again.

**Comment by yn5** [comment]
You were completely right, I was still on 1.4. May I threfore suggest the following pull request: https://github.com/linssen/docker-craft-cms/pull/4 ;)

**Comment by linssen** [comment]
Fixed in #4.
